/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedSuperAdminRouteRouteImport } from './routes/_protected/super-admin/route'
import { Route as ProtectedSuperAdminUsersRouteRouteImport } from './routes/_protected/super-admin/users/route'
import { Route as ProtectedSuperAdminModelltestsIndexRouteImport } from './routes/_protected/super-admin/modelltests/index'
import { Route as ProtectedSuperAdminGroupsIndexRouteImport } from './routes/_protected/super-admin/groups/index'
import { Route as ProtectedSuperAdminExamsIndexRouteImport } from './routes/_protected/super-admin/exams/index'
import { Route as ProtectedSuperAdminDashboardIndexRouteImport } from './routes/_protected/super-admin/dashboard/index'
import { Route as ProtectedSuperAdminUsersStudentsRouteRouteImport } from './routes/_protected/super-admin/users/students/route'
import { Route as ProtectedSuperAdminModelltestsModelltestIdIndexRouteImport } from './routes/_protected/super-admin/modelltests/$modelltestId/index'
import { Route as ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRouteImport } from './routes/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/index'
import { Route as ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRouteImport } from './routes/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
import { Route as ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRouteImport } from './routes/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuperAdminRouteRoute =
  ProtectedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSuperAdminUsersRouteRoute =
  ProtectedSuperAdminUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminModelltestsIndexRoute =
  ProtectedSuperAdminModelltestsIndexRouteImport.update({
    id: '/modelltests/',
    path: '/modelltests/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminGroupsIndexRoute =
  ProtectedSuperAdminGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminExamsIndexRoute =
  ProtectedSuperAdminExamsIndexRouteImport.update({
    id: '/exams/',
    path: '/exams/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminDashboardIndexRoute =
  ProtectedSuperAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminUsersStudentsRouteRoute =
  ProtectedSuperAdminUsersStudentsRouteRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => ProtectedSuperAdminUsersRouteRoute,
  } as any)
const ProtectedSuperAdminModelltestsModelltestIdIndexRoute =
  ProtectedSuperAdminModelltestsModelltestIdIndexRouteImport.update({
    id: '/modelltests/$modelltestId/',
    path: '/modelltests/$modelltestId/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute =
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRouteImport.update(
    {
      id: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/',
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/',
      getParentRoute: () => ProtectedSuperAdminRouteRoute,
    } as any,
  )
const ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute =
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRouteImport.update(
    {
      id: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new',
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new',
      getParentRoute: () => ProtectedSuperAdminRouteRoute,
    } as any,
  )
const ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute =
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRouteImport.update(
    {
      id: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit',
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit',
      getParentRoute: () => ProtectedSuperAdminRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRouteRouteWithChildren
  '/super-admin/users/students': typeof ProtectedSuperAdminUsersStudentsRouteRoute
  '/super-admin/dashboard/': typeof ProtectedSuperAdminDashboardIndexRoute
  '/super-admin/exams/': typeof ProtectedSuperAdminExamsIndexRoute
  '/super-admin/groups/': typeof ProtectedSuperAdminGroupsIndexRoute
  '/super-admin/modelltests/': typeof ProtectedSuperAdminModelltestsIndexRoute
  '/super-admin/modelltests/$modelltestId/': typeof ProtectedSuperAdminModelltestsModelltestIdIndexRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRouteRouteWithChildren
  '/super-admin/users/students': typeof ProtectedSuperAdminUsersStudentsRouteRoute
  '/super-admin/dashboard': typeof ProtectedSuperAdminDashboardIndexRoute
  '/super-admin/exams': typeof ProtectedSuperAdminExamsIndexRoute
  '/super-admin/groups': typeof ProtectedSuperAdminGroupsIndexRoute
  '/super-admin/modelltests': typeof ProtectedSuperAdminModelltestsIndexRoute
  '/super-admin/modelltests/$modelltestId': typeof ProtectedSuperAdminModelltestsModelltestIdIndexRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute
  '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_protected/super-admin/users': typeof ProtectedSuperAdminUsersRouteRouteWithChildren
  '/_protected/super-admin/users/students': typeof ProtectedSuperAdminUsersStudentsRouteRoute
  '/_protected/super-admin/dashboard/': typeof ProtectedSuperAdminDashboardIndexRoute
  '/_protected/super-admin/exams/': typeof ProtectedSuperAdminExamsIndexRoute
  '/_protected/super-admin/groups/': typeof ProtectedSuperAdminGroupsIndexRoute
  '/_protected/super-admin/modelltests/': typeof ProtectedSuperAdminModelltestsIndexRoute
  '/_protected/super-admin/modelltests/$modelltestId/': typeof ProtectedSuperAdminModelltestsModelltestIdIndexRoute
  '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute
  '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute
  '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit': typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/login'
    | '/register'
    | '/super-admin/users'
    | '/super-admin/users/students'
    | '/super-admin/dashboard/'
    | '/super-admin/exams/'
    | '/super-admin/groups/'
    | '/super-admin/modelltests/'
    | '/super-admin/modelltests/$modelltestId/'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/super-admin'
    | '/login'
    | '/register'
    | '/super-admin/users'
    | '/super-admin/users/students'
    | '/super-admin/dashboard'
    | '/super-admin/exams'
    | '/super-admin/groups'
    | '/super-admin/modelltests'
    | '/super-admin/modelltests/$modelltestId'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts'
    | '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/super-admin'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_protected/super-admin/users'
    | '/_protected/super-admin/users/students'
    | '/_protected/super-admin/dashboard/'
    | '/_protected/super-admin/exams/'
    | '/_protected/super-admin/groups/'
    | '/_protected/super-admin/modelltests/'
    | '/_protected/super-admin/modelltests/$modelltestId/'
    | '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
    | '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/'
    | '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/super-admin': {
      id: '/_protected/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof ProtectedSuperAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/super-admin/users': {
      id: '/_protected/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof ProtectedSuperAdminUsersRouteRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/modelltests/': {
      id: '/_protected/super-admin/modelltests/'
      path: '/modelltests'
      fullPath: '/super-admin/modelltests/'
      preLoaderRoute: typeof ProtectedSuperAdminModelltestsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/groups/': {
      id: '/_protected/super-admin/groups/'
      path: '/groups'
      fullPath: '/super-admin/groups/'
      preLoaderRoute: typeof ProtectedSuperAdminGroupsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/exams/': {
      id: '/_protected/super-admin/exams/'
      path: '/exams'
      fullPath: '/super-admin/exams/'
      preLoaderRoute: typeof ProtectedSuperAdminExamsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/dashboard/': {
      id: '/_protected/super-admin/dashboard/'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard/'
      preLoaderRoute: typeof ProtectedSuperAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/users/students': {
      id: '/_protected/super-admin/users/students'
      path: '/students'
      fullPath: '/super-admin/users/students'
      preLoaderRoute: typeof ProtectedSuperAdminUsersStudentsRouteRouteImport
      parentRoute: typeof ProtectedSuperAdminUsersRouteRoute
    }
    '/_protected/super-admin/modelltests/$modelltestId/': {
      id: '/_protected/super-admin/modelltests/$modelltestId/'
      path: '/modelltests/$modelltestId'
      fullPath: '/super-admin/modelltests/$modelltestId/'
      preLoaderRoute: typeof ProtectedSuperAdminModelltestsModelltestIdIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/': {
      id: '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/'
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts'
      fullPath: '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/'
      preLoaderRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new': {
      id: '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
      fullPath: '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/new'
      preLoaderRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit': {
      id: '/_protected/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
      path: '/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
      fullPath: '/super-admin/modelltests/$modelltestId/modules/$modelltestModuleId/parts/$partId/edit'
      preLoaderRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
  }
}

interface ProtectedSuperAdminUsersRouteRouteChildren {
  ProtectedSuperAdminUsersStudentsRouteRoute: typeof ProtectedSuperAdminUsersStudentsRouteRoute
}

const ProtectedSuperAdminUsersRouteRouteChildren: ProtectedSuperAdminUsersRouteRouteChildren =
  {
    ProtectedSuperAdminUsersStudentsRouteRoute:
      ProtectedSuperAdminUsersStudentsRouteRoute,
  }

const ProtectedSuperAdminUsersRouteRouteWithChildren =
  ProtectedSuperAdminUsersRouteRoute._addFileChildren(
    ProtectedSuperAdminUsersRouteRouteChildren,
  )

interface ProtectedSuperAdminRouteRouteChildren {
  ProtectedSuperAdminUsersRouteRoute: typeof ProtectedSuperAdminUsersRouteRouteWithChildren
  ProtectedSuperAdminDashboardIndexRoute: typeof ProtectedSuperAdminDashboardIndexRoute
  ProtectedSuperAdminExamsIndexRoute: typeof ProtectedSuperAdminExamsIndexRoute
  ProtectedSuperAdminGroupsIndexRoute: typeof ProtectedSuperAdminGroupsIndexRoute
  ProtectedSuperAdminModelltestsIndexRoute: typeof ProtectedSuperAdminModelltestsIndexRoute
  ProtectedSuperAdminModelltestsModelltestIdIndexRoute: typeof ProtectedSuperAdminModelltestsModelltestIdIndexRoute
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute
  ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute: typeof ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute
}

const ProtectedSuperAdminRouteRouteChildren: ProtectedSuperAdminRouteRouteChildren =
  {
    ProtectedSuperAdminUsersRouteRoute:
      ProtectedSuperAdminUsersRouteRouteWithChildren,
    ProtectedSuperAdminDashboardIndexRoute:
      ProtectedSuperAdminDashboardIndexRoute,
    ProtectedSuperAdminExamsIndexRoute: ProtectedSuperAdminExamsIndexRoute,
    ProtectedSuperAdminGroupsIndexRoute: ProtectedSuperAdminGroupsIndexRoute,
    ProtectedSuperAdminModelltestsIndexRoute:
      ProtectedSuperAdminModelltestsIndexRoute,
    ProtectedSuperAdminModelltestsModelltestIdIndexRoute:
      ProtectedSuperAdminModelltestsModelltestIdIndexRoute,
    ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute:
      ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsNewRoute,
    ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute:
      ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsIndexRoute,
    ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute:
      ProtectedSuperAdminModelltestsModelltestIdModulesModelltestModuleIdPartsPartIdEditRoute,
  }

const ProtectedSuperAdminRouteRouteWithChildren =
  ProtectedSuperAdminRouteRoute._addFileChildren(
    ProtectedSuperAdminRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedSuperAdminRouteRoute: typeof ProtectedSuperAdminRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSuperAdminRouteRoute: ProtectedSuperAdminRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
